### ISSUE TITLE
ESA SNAP Toolbox image

### ISSUE THREAD

**Issue by Scartography** [eurodatacube/base-images#1]
Custom processing to offer a SNAP image, maybe even in combination with other tools. Remote Sensing users might be interested to use GPT so that they don't need to use/invest into own hardware.

Example (Food for thought): [OST Dockerfile](https://github.com/ESA-PhiLab/OpenSarToolkit/blob/master/Dockerfile)
Replace OST git package with something else for instance etc.

**Comment by achtsnits** [comment]
specific libraries like SNAP or orfeo toolbox may be included in customer specific base images but not in generic base image
