### ISSUE TITLE
breaking changes in geodb -> getting started notebooks must be updated

### ISSUE THREAD

**Issue by achtsnits** [eurodatacube/base-images#2]
there are breaking changes in geodb which will be included in base-images > v0.18.0

geodb getting started notebooks of Euro Data Cube marketplace mus tbe adapted for https://github.com/dcs4cop/xcube-geodb/tree/master/notebooks

**Comment by totycro** [comment]
Notebooks in git master and dev are updated. When the new base image is deployed to production, the notebooks must be updated there as well.
