### ISSUE TITLE
Version control codes and notebooks on Jupyterlab server

### ISSUE THREAD

**Issue by shexiaogui** [eurodatacube/base-images#3]
I am a user of EDC and I started the jupyterlab server provided as an app on marketplace. The notebooks and code I created cannot be commited to github and I also cannot clone any repo from github. It makes the development inconvenient. Is there any way to sync with version control ?

**Comment by totycro** [comment]
Hi shexiaogui,

We currently don't feature a graphical user interface within jupyterlab.

One way to clone and commit back to a git repository however is to use the terminal in jupyterlab. There you have access to the usual git command line line interface, so you can  "git clone", "git commit", etc. there.

Are you looking for a graphical user interface such as this? https://github.com/jupyterlab/jupyterlab-git

Best regards,
totycro

**Comment by StefanBrand** [comment]
In the launcher, you can open a Terminal tab (see below) and from there you can use `git` commands as in your local Terminal window. You can find some resources here: https://try.github.io/

![Screenshot of Jupyter Lab Launcher with Terminal highlighted](https://user-images.githubusercontent.com/8948865/82303029-b05be280-99ba-11ea-861e-a98f9f536f3c.png)

For example, cloning the https://github.com/eurodatacube/notebooks repo looks like this:

![Screenshot of terminal in Jupyter Lab cloning a Github repo](https://user-images.githubusercontent.com/8948865/82304646-e00bea00-99bc-11ea-86fe-208676f8fb0c.png)

**Comment by shexiaogui** [comment]
Thank you for your quick reply ! I didn't release git was installed inside this docker image. My mistake. 
Have a good day !

**Comment by totycro** [comment]
I'm reopening this since it's probably useful to have the jupyterlab git extension installed as an additional way of using git.

**Comment by totycro** [comment]
The jupyterlab git extension is now available. You can find it in the main menu and in the menu to the left.
